spring:
  profiles:
    active: native
  application:
    name: config-servier
  cloud:
    config:
      server:
        native:
          search-locations: classpath://configurations


server:
  port: 8888
